apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api-app
  template:
    metadata:
      labels:
        app: flask-api-app
    spec:
      containers:
      - name: flask-api-app
        image: gcr.io/docker-gke-436022/dsassingment1-flask-api-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.29.0
        command: ["/cloud_sql_proxy",
                  "-instances=docker-gke-436022:us-east1:db-flask=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-secrets
          mountPath: /secrets/cloudsql
      volumes:  # Fixed indentation of volumes
      - name: cloudsql-secrets
        secret: 
          secretName: cloudsql-instance-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30001
  selector:
    app: flask-api-app
